---
name: Unit Tests with released Puppet gem

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit_tests_with_released_puppet_gem:
    name: ${{ matrix.os_type }} / Puppet${{ matrix.puppet_version }} gem / Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        os: [ 'ubuntu-18.04', 'macos-10.15', 'windows-2016' ]
        puppet_version: [ 5, 6 ]
        include:
          - puppet_version: 5
            ruby: 2.4
          - puppet_version: 6
            ruby: 2.5

          - os: 'ubuntu-18.04'
            os_type: 'Linux'
          - os: 'macos-10.15'
            os_type: 'macOS'
          - os: 'windows-2016'
            os_type: 'Windows'

    runs-on: ${{ matrix.os }}
    env:
      PUPPET_GEM_VERSION: ~> ${{ matrix.puppet_version }}.0
    steps:
      - name: Checkout current PR code
        uses: actions/checkout@v2

      - name: Install ruby version ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Prepare testing environment with bundler
        run: |
          git config --global core.longpaths true
          bundle update --jobs 4 --retry 3

      - name: Run unit tests
        run: bundle exec rake parallel_spec
